// Auth
export const SIGNUP_WITH_GOOGLE_SCREEN = 'SIGNUP_WITH_GOOGLE_SCREEN';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';

// App
export const NEWS_LIST_SCREEN = 'NEWS_LIST_SCREEN';
export const NEWS_DETAIL_SCREEN = 'NEWS_DETAIL_SCREEN';
